<?php if($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs">
        <?php $showMarkup = true; if($showMarkup==true): ?>
            <ul>
                <?php $i = 0;
                foreach ($crumbs as $_crumbName => $_crumbInfo):
                    $i++;
                    $showItemscope = false;
                    $itemscopeData = '';
                    if($_crumbInfo['link'] && !$_crumbInfo['last'] && $i!=1):
                        $showItemscope = true;
                        $itemscopeData = ' itemscope itemtype="http://data-vocabulary.org/Breadcrumb"';
                    endif;
                    ?>
                    <li class="<?php echo $_crumbName ?>" <?php echo $itemscopeData; ?>>
                        <?php if ($_crumbInfo['link']): ?>
                            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>" <?php if ($showItemscope): ?>itemprop="url"<?php endif; ?>>
                                <span <?php if ($showItemscope): ?>itemprop="title"<?php endif; ?>><?php echo $this->escapeHtml($_crumbInfo['label']) ?></span>
                            </a>
                        <?php elseif ($_crumbInfo['last']): ?>
                            <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
                        <?php endif; ?>
                        <?php if (!$_crumbInfo['last']): ?>
                            <span>/ </span>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <ul>
                <?php foreach ($crumbs as $_crumbName => $_crumbInfo): ?>
                    <li class="<?php echo $_crumbName ?>">
                        <?php if ($_crumbInfo['link']): ?>
                            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
                        <?php elseif ($_crumbInfo['last']): ?>
                            <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
                        <?php endif; ?>
                        <?php if (!$_crumbInfo['last']): ?>
                            <span>/ </span>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>
